# fly.toml app configuration file generated for future-strapi on 2023-08-29T14:39:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "future-strapi"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="future_data"
  destination="/data"
